/* ================================================================
   products.js  — product data module
   Exposed as window.PRODUCTS (no build step needed).
   ================================================================ */
window.PRODUCTS = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    category: "electronics",
    price: 4999,
    originalPrice: 7999,
    rating: 4.5,
    reviews: 312,
    stock: 15,
    badge: "Best Seller",
    description: "40-hour battery, active noise cancellation, Bluetooth 5.3, and multipoint connection. USB-C charging, fold-flat design, and comfortable enough for long sessions. The kind of headphones that make you realise your old ones were just bad.",
    features: ["40hr battery", "ANC", "BT 5.3", "USB-C", "Multipoint"],
    image: "🎧",
    color: "linear-gradient(135deg,#1c1e2a,#2c2a3a)"
  },
  {
    id: 2,
    name: "Mechanical Keyboard TKL",
    category: "electronics",
    price: 3499,
    originalPrice: 4999,
    rating: 4.7,
    reviews: 189,
    stock: 8,
    badge: "Popular",
    description: "Tenkeyless layout, hot-swappable switches, per-key RGB, gasket mount. Compatible with Windows, macOS, Linux. South-facing LEDs, PBT double-shot keycaps, detachable USB-C cable.",
    features: ["Hot-swap", "Gasket mount", "Per-key RGB", "TKL", "PBT keycaps"],
    image: "⌨",
    color: "linear-gradient(135deg,#2a1c1c,#3a2a2a)"
  },
  {
    id: 3,
    name: "27\" 4K IPS Monitor",
    category: "electronics",
    price: 22999,
    originalPrice: 29999,
    rating: 4.6,
    reviews: 97,
    stock: 5,
    badge: "Sale",
    description: "3840×2160 at 60Hz, IPS panel, 99% sRGB, DisplayPort + 2× HDMI + USB-C with 65W power delivery. Height and tilt adjustable. Proper colour accuracy out of the box — no calibration needed.",
    features: ["4K 60Hz", "IPS", "99% sRGB", "USB-C PD", "Height adjust"],
    image: "🖥",
    color: "linear-gradient(135deg,#1c2a2a,#2a3a3a)"
  },
  {
    id: 4,
    name: "Ergonomic Mesh Desk Chair",
    category: "furniture",
    price: 12999,
    originalPrice: 17999,
    rating: 4.4,
    reviews: 224,
    stock: 12,
    badge: null,
    description: "Mesh back, adjustable lumbar support, 4D armrests, seat depth slider. Rated for 130kg. The chair that makes you realise how bad your previous one was — in a good way.",
    features: ["Mesh back", "4D armrests", "Lumbar adjust", "Seat slide", "130kg rated"],
    image: "🪑",
    color: "linear-gradient(135deg,#1c2a1e,#2a3a2c)"
  },
  {
    id: 5,
    name: "Adjustable Standing Desk",
    category: "furniture",
    price: 18499,
    originalPrice: 23999,
    rating: 4.3,
    reviews: 156,
    stock: 7,
    badge: null,
    description: "Electric height adjust 62–127cm, 3-preset memory, anti-collision sensor, bamboo surface. Rated for 80kg. Doesn't wobble at standing height — which is rarer than it should be.",
    features: ["Electric adjust", "3 presets", "Anti-collision", "Bamboo top", "80kg rated"],
    image: "🗂",
    color: "linear-gradient(135deg,#2a2210,#3a3018)"
  },
  {
    id: 6,
    name: "Portable SSD 1TB",
    category: "electronics",
    price: 5999,
    originalPrice: 7499,
    rating: 4.8,
    reviews: 441,
    stock: 30,
    badge: "Top Rated",
    description: "1050MB/s read, 1000MB/s write, USB 3.2 Gen 2. Rugged aluminium shell rated for 3m drops. Bus-powered, fits in a shirt pocket. Comes with both USB-C and USB-A cables.",
    features: ["1050MB/s", "USB 3.2 Gen2", "3m drop-proof", "Aluminium", "Bus-powered"],
    image: "💾",
    color: "linear-gradient(135deg,#221c2a,#322a3a)"
  },
  {
    id: 7,
    name: "LED Desk Lamp + Wireless Charger",
    category: "accessories",
    price: 2299,
    originalPrice: 3499,
    rating: 4.2,
    reviews: 88,
    stock: 22,
    badge: null,
    description: "5 colour temperatures, 10 brightness levels, 10W wireless charging pad in the base, USB-A port for accessories. Memory function keeps your last settings. Doesn't tip over.",
    features: ["5 colour temps", "10 brightness", "10W wireless", "USB-A port", "Memory"],
    image: "💡",
    color: "linear-gradient(135deg,#2a2a1c,#3a3a2c)"
  },
  {
    id: 8,
    name: "Webcam 1080p 60fps",
    category: "electronics",
    price: 3999,
    originalPrice: 5499,
    rating: 4.4,
    reviews: 203,
    stock: 18,
    badge: null,
    description: "1080p at 60fps, autofocus, dual stereo mics with noise reduction, physical privacy cover. Plug-and-play USB-A — works on Windows, Mac, and Linux with zero setup.",
    features: ["1080p 60fps", "Autofocus", "Dual mics", "Privacy cover", "Plug & play"],
    image: "📷",
    color: "linear-gradient(135deg,#2a1c2a,#3a2a3a)"
  },
  {
    id: 9,
    name: "Hardcover Notebook Set A5",
    category: "accessories",
    price: 599,
    originalPrice: 799,
    rating: 4.6,
    reviews: 512,
    stock: 100,
    badge: null,
    description: "Set of 3 hardcover A5 notebooks, 200 pages each, dotted grid, 100gsm paper, ribbon bookmark, elastic closure. No ghosting or bleed-through with most fountain pens.",
    features: ["Set of 3", "200 pages", "Dotted grid", "100gsm", "Ribbon bookmark"],
    image: "📓",
    color: "linear-gradient(135deg,#1c2a1e,#2c3a2e)"
  },
  {
    id: 10,
    name: "USB-C Hub 7-in-1",
    category: "accessories",
    price: 1799,
    originalPrice: 2499,
    rating: 4.3,
    reviews: 334,
    stock: 45,
    badge: "New",
    description: "4K HDMI, 2× USB-A 3.0, SD + microSD reader, 100W USB-C PD passthrough, gigabit ethernet. Compact aluminium body that sits flush with any USB-C laptop.",
    features: ["4K HDMI", "2× USB-A 3.0", "SD + microSD", "100W PD", "Gigabit LAN"],
    image: "🔌",
    color: "linear-gradient(135deg,#1c1c2a,#2a2c3a)"
  },
  {
    id: 11,
    name: "Blue Light Blocking Glasses",
    category: "accessories",
    price: 899,
    originalPrice: 1299,
    rating: 4.1,
    reviews: 267,
    stock: 60,
    badge: null,
    description: "TR90 frame, anti-reflective coating, filters ~40% blue light without colour distortion. Non-prescription. Comes in a hard case. Lightweight enough to forget you're wearing them.",
    features: ["40% blue block", "AR coating", "TR90 frame", "Non-prescription", "Hard case"],
    image: "👓",
    color: "linear-gradient(135deg,#2a1e1c,#3a2e2c)"
  },
  {
    id: 12,
    name: "Bamboo Desk Organiser",
    category: "furniture",
    price: 1299,
    originalPrice: 1799,
    rating: 4.5,
    reviews: 178,
    stock: 33,
    badge: null,
    description: "Natural bamboo, 6 compartments, phone slot, cable management hole at the back, removable inner tray. Actually keeps things tidy rather than just moving the mess somewhere else.",
    features: ["6 compartments", "Phone slot", "Cable hole", "Removable tray", "Natural bamboo"],
    image: "🗃",
    color: "linear-gradient(135deg,#2a2010,#3a3020)"
  }
];
